spring:
  application:
    name: hospital
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/hospital
    username: bankuser
    password: numsbank
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
