spring:
  application:
    name: hospital
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
